### ISSUE TITLE
Seems to not work any longer with iOS 11 SDK

### ISSUE THREAD

**Issue by neilyoung** [chrismiles/CMPopTipView#129]
Worked fine until I updated to XCode 9.
Now it is just popping up once, then most the time never again.

**Comment by neilyoung** [comment]
More precisely:
 `(void)presentPointingAtBarButtonItem:(UIBarButtonItem *)barButtonItem animated:(BOOL)animated `

does not show up, if the UIBarButtonItem is child of a bottom toolbar.

**Comment by yanglk** [comment]
I fix it by add a few lines in 
`- (void)presentPointingAtBarButtonItem:(UIBarButtonItem *)barButtonItem animated:(BOOL)animated`
after the line `UIView *targetSuperview = [targetView superview];`,just add these lines:
`while (![targetSuperview isKindOfClass:[UINavigationBar class]]) {
        targetSuperview = [targetSuperview superview];
 }`

**Comment by neilyoung** [comment]
@yanglk Does that work for < iOS 11 as well? This is exactly the way I was trying to fix it to no avail. Did choose another project then (NMEasyTipView, https://github.com/nitishmakhija/EasyTipView) which did it for me.

**Comment by yanglk** [comment]
@neilyoung yes, for < iOS 11, the while condition will not fulfilled, so it won't do anything.

**Comment by dobiho5** [comment]
@yanglk Do you have any plan to update for iOS 11
I add above code after UIVIew *~ , but it does not worked on iOS 11 bottom toolbar.

**Comment by dobiho5** [comment]
@yanglk I resolved my problem for UIToolbar as your quick added code like this 

Would you update your cocoa pod?

UIView *targetSuperview = [targetView superview];
    while (![targetSuperview isKindOfClass:[UIToolbar class]]) { targetSuperview = [targetSuperview superview]; }

**Comment by kleinlieu** [comment]
I can update it this weekend for you all

**Comment by dobiho5** [comment]
@yanglk @kleinlieu I got found, dismissAnimated does not work.  please solve this also. I have searched other tool tip, but CMPopTipView is best I think.

**Comment by dobiho5** [comment]
@kleinlieu dismiss is not issue. I fixed execute dismiss in main thread in iOS 11.

**Comment by kleinlieu** [comment]
Hey @dobiho5 @neilyoung @yanglk this should be fixed in the latest release tagged v2.3.1. Feel free to pull from master or find it on CocoaPods.
