### ISSUE TITLE
Issues when pointing to a subview in a UITableViewCell

### ISSUE THREAD

**Issue by willniu** [chrismiles/CMPopTipView#21]
When pointing a poptip view to a subview (say, a UIButton) in a UITableViewCell, the "inView" parameter has to be the cell in order to have the poptip view positions correctly. However, that presents a couple of issues:
1. dismissTapAnywhere no longer works (well, maybe it does, but not as I would expect...), as the tap has to be within the cell. I resolve this by including an invisible button covering the whole screen.
2. the table section title and cell borders are now on top of the poptip view. I am not sure how to resolve this issue.

Could you please provide a fix or a workaround?

Cheers,
William

**Comment by Sempercon1** [comment]
Added a custom view , the custom view and popover view background color should be transparent but if i cleared color of custom view by default it showed as black . How to rectify this.
