### ISSUE TITLE
Ability to add a buton outside of the tooltipview

### ISSUE THREAD

**Issue by revolter** [chrismiles/CMPopTipView#91]
I'm trying to create a button that overflows the tooltip like this:

![screen shot 2015-02-27 at 14 19 30](https://cloud.githubusercontent.com/assets/5748627/6412383/b21ec78c-be8b-11e4-9d9f-5f2253029166.png)

But the touch event is not called for the upper part of the button. How can I make it work without modifying the library? I tried overriding `pointInside:withEvent:` but it doesn't get called.

I'm sorry if this doesn't regards this library directly but I can't figure it out how to do it.

**Comment by chrismiles** [comment]
If the button is a subview of the popup view, then any region of the button outside of the popup view's bounds won't receive touch events (even though it will be drawn). You have to keep the button inside its parents bounds.

**Comment by revolter** [comment]
I managed to do that by overriding the `pointInside:withEvent:` method for the popup's view.
